export const actionsTypes = {
  ADD_TASK: "ADD_TASK",
  REMOVE_TASK: "REMOVE_TASK",
  MARK_COMPLETE_TASK: "MARK_COMPLETE_TASK",
  ACTIVE_FILTER_TASKS: "ACTIVE_FILTER_TASKS",
  COMPLETE_FILTER_TASKS: "COMPLETE_FILTER_TASKS",
  ALL_FILTER_TASKS: " ALL_FILTER_TASKS",
};
